### PR TITLE
feat:  form questions view, closes #47

### LINKED ISSUE #47: Create form - create form questions view

### PR DESCRIPTION
**Pull request by KristelKolkanen**

### CODE REVIEW

**Comment by stellamarii** [comment]
Feature itself is working well and is functional, but I have some suggestions: 

They are just suggestions, no need to change anything if you don't want to ☺

1. Tooltip is streched out, I would add sx to it
```
sx={{
  width: 'fit-content'
}}
```
image

2. `<a>` element is actually not needed for Button links. At the moment the clickable area is a lot bigger than text
```
<Button
  href="/"
  className="py-2 px-4 rounded-md no-underline"
  variant="contained"
  color="primary"
  sx={{
    width: 'fit-content'
  }}
  >
    Lõpeta
</Button>
```
image

3. Instead of `<br />`, maybe adding `sx={{my: 2}}` to `TextField` elements would be better, so there's no need for extra HTML elements

**Review by Treimart — APPROVED** [review]
Well done, this technically has the bare minimum we need 🙂

It would be nice to have an option for navigating between questions. This should be possible by adding code for fetching questions from database and inserting them to the textfield as a placeholder. Another method would be to use an index for each question (similar to method used in `components/ViewQuestion.jsx`).
The form textfields should also clear themselves out (delete text) each time the question is saved.

These changes can be added later, so I'll approve this now 😊

**Comment by KristelKolkanen** [comment]
@stellamarii @Treimart still working on it, going to get it better before merging

**Comment by Treimart** [comment]
This already looks much better and user friendly 😊

The ability to see your saved questions, as well as the form cleaning itself out each time a question is saved is a much better UX. However (unless I somehow missed it) in my opinion, the ability to navigate between saved questions (so that an user could edit their previous questions and answers) would be crucial, but this can also be added later after creating a new issue.

In terms of styling, I would shift the saved questions view to the left and have the form parallel to it on the right side. But this can also be done later once we focus more on frontend and styling.

These are just a few suggestions. Since I already gave an approve on it previously, you'd have to wait for @stellamarii feedback.

**Review by Treimart — APPROVED** [review]
Well done!

**Review by stellamarii — APPROVED** [review]

**Pull request merged**
