### PR TITLE
style: horizontal allignment for form components, closes #108

### LINKED ISSUE #108: Style: horizontal grid for components
Redesign `ShowUserFavorites` and `ShowUserForms` comonents to be displayed horizontally.

### PR DESCRIPTION
**Pull request by Treimart**
`ShowUserFavorites` and `ShowUserForms` components now display forms horizontally.
Relocated components in `app/profile` page under child `Grid` element to better fit with horizontal allignment.
Small changes to `gap` props.

### CODE REVIEW

**Comment by Treimart** [comment]
> Sinu lemmikud is now h4, others are h3, they all should be h3
> If you are already changing profile page, I suggest to put PROFIILI ANMDED also as Typography and variant h1
> Deleting icon would look better if it were on the other side as in the picture below. ShowUserForms.tsx line 146 could be replaced with justifyContent: "space-between"

These are all great suggestions! I'll keep editing the page and components while taking the feedback into account 😊

**Comment by Treimart** [comment]
I have now commited my most recent changes. I ended up changing all `Typography` variants to `h4`, since `h3` seemed a little oversized for me (might be just me, so let me know if any of you liked the `h3` variant better). Added `Typography` to `PROFIILI ANDMED` as well, but `h1` was ridiculously overscaled for it. Agan, `h4` variant seemed like the most suitable option to me.

Feel free to request changes if anything still needs to be redesigned or relocated 😁

**Comment by stellamarii** [comment]
Typography variants should be h1 and h3. We need to adjust the sizes when we do styling for MUI elements. Then all our h1 (and h2, Buttons etc.) elements will be in the same size throughout the page. At the moment it's okay if they do not look right

**Review by stellamarii — APPROVED** [review]
I strongly suggest to use h1 in page title

But otherwise it works well, and I approve, if you don't want to change, then merge

**Comment by Treimart** [comment]
> Typography variants should be h1 and h3.

Sorry, I just didn't have a moment to change the variants like you requested.

> We need to adjust the sizes when we do styling for MUI elements.

> But otherwise it works well, and I approve,

Since you already gave an approve, I'll just merge this for now. Once we start styling these MUI elements and adjust their size, we can change these back to `h1` and `h3` variants 😊

**Pull request merged**
